apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: saga-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: povarovaa/inventory-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@db:5432/inventorydb"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: saga-app
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: inventory-service
