services:
  react-client:
    image: povarovaa/circuit-breaker-frontend:latest
    ports:
      - '80:3000'
    environment:
      - REACT_APP_BACKEND_URL=http://10.102.180.52/
  flask-server:
    image: povarovaa/circuit-breaker-backend:latest
    ports:
      - '5000:5000'