apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: kafka
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: <your-registry>/kafka-consumer:latest
          env:
            - name: KAFKA_BROKER
              value: "my-cluster-kafka-bootstrap.kafka:9092"
            - name: TOPIC_NAME
              value: "example-topic"
